### ISSUE TITLE
[REditorSupport.R] No update after change of publishId

### ISSUE THREAD

**Issue by benz0li** [open-vsx/publish-extensions#591]
See https://github.com/REditorSupport/vscode-R/issues/690#issuecomment-1123702750 ff

**Comment by benz0li** [comment]
@filiptronicek Is there something to be done in this repository, e.g. migrate the extension to the new publishId?

@renkun-ken This seems to be the right time to verify the extension in the Open VSX Registry.

**Comment by benz0li** [comment]
@filiptronicek @renkun-ken Please get in touch with each other regarding https://github.com/REditorSupport/vscode-R/issues/524 to ensure a smooth transition.

Thank you.

**Comment by renkun-ken** [comment]
I'd like to hear what should be done on my side?

**Comment by filiptronicek** [comment]
Hi there @benz0li, thanks for bringing this to our attention. 

@renkun-ken I will remove the old version (`Ikuyadeu.r`) from auto-publishing. You should already be the owner of the `REditorSupport` namespace [[1](https://github.com/EclipseFdn/open-vsx.org/issues/341), so the process for publishing should be straight forward: publish the extension from the https://github.com/REditorSupport/vscode-R repository. 

It seems that there is already a publishing GitHub Action workflow that publishes to the VS Code Marketplace and so you should be fine with just adding a repo secret with the Open VSX  [access token](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#3-create-an-access-token) and then replace the `publish` job with the following:

```yaml
  publish:
    name: Publish
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node $SCRIPT_DIR/enableWebpack.js
      - run: yarn install
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}

```
